# Generated by Django 3.1.1 on 2020-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dos_website',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
