# Generated by Django 3.1.1 on 2020-11-16 16:22

from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('dos_website', '0002_auto_20201116_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='dos_website',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
